### ISSUE TITLE
add isk compensation when item value differs too much

### ISSUE THREAD

**Issue by evilwarlock** [yehzhang/tea-eaccounting-assistant#3]
set a threshold d that when 
V(item got)-V(payout)/V > d,
provide isk pay/req for the distributor

**Comment by evilwarlock** [comment]
also add discounted ratio(item->isk), .75 as default

**Comment by evilwarlock** [comment]
add option to use isk compensation on website
simplify need page

**Comment by yehzhang** [comment]
Good call. I will work on this issue in the following days, if you have not claimed it yet.

**Comment by yehzhang** [comment]
Done.
